// Data originally from cold banana backend API
export const apiCall = [
    [
        {
            id: 6,
            product_name: "Yoga Mat",
            image: "images/product-images/yoga-mats.jpg",
            price: 9.99,
            stock_count: 6,
        },
        {
            id: 1,
            product_name: "Resistance Band",
            image: "images/product-images/resistance-bands.jpg",
            price: 4.49,
            stock_count: 20,
        },
        {
            id: 3,
            product_name: "Wrist & Ankle Weights",
            image: "images/product-images/wrist-weights.jpg",
            price: 18,
            stock_count: 79,
        },
        {
            id: 4,
            product_name: "Dumbbell Set",
            image: "images/product-images/dumbbell.jpg",
            price: 25,
            stock_count: 0,
        },
        {
            id: 7,
            product_name: "Weighted Hoop",
            image: "images/product-images/weighted-hoop.jpg",
            price: 27,
            stock_count: 19,
        },
        {
            id: 10,
            product_name: "Cork Wheel",
            image: "images/product-images/cork-wheel.jpg",
            price: 45,
            stock_count: 58,
        },
        {
            id: 8,
            product_name: "Balance Pad",
            image: "images/product-images/balance-pad.jpg",
            price: 8,
            stock_count: 38,
        },
        {
            id: 9,
            product_name: "Swiss Ball",
            image: "images/product-images/swiss-ball.jpg",
            price: 19.99,
            stock_count: 43,
        },
        {
            id: 10,
            product_name: "Weighted Ball",
            image: "images/product-images/weighted-ball.jpg",
            price: 8.99,
            stock_count: 58,
        },
        {
            id: 10,
            product_name: "Yoga Bricks",
            image: "images/product-images/yoga-bricks.jpg",
            price: 7,
            stock_count: 58,
        },
        {
            id: 5,
            product_name: "Foam Roller",
            image: "images/product-images/foam-roller.jpg",
            price: 24.99,
            stock_count: 39,
        },
        {
            id: 2,
            product_name: "Resistance Ring",
            image: "images/product-images/resistance-ring.jpg",
            price: 10,
            stock_count: 87,
        },
    ],
];
